site_name: PIIE
theme:
  name: material
  palette:
    primary: deep orange
    scheme: slate
nav:
  - Home: index.md
  - About: about.md
  - PIIE: PIIE.md
  - Documentation: Documentation.md
extra_css: 
  - Stylesheets/color.css