site_name: PIIE
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
  favicon: img/favicon.png
  logo: img/favicon.png
nav:
  - Home: index.md
  - About: about.md
  - Download: download.md
  - Documentation: documentation.md

